#PROMETHEUS
PROMETHEUS_URL: "http://127.0.0.1:9090"
START_TIME: datetime.datetime.strptime("2021-06-22 18:15:00", "%Y-%m-%d %H:%M:%S")
END_TIME: datetime.datetime.strptime("2021-06-22 18:20:00", "%Y-%m-%d %H:%M:%S")
METRIC_NAME: "request_duration_seconds_count"
QUERY: 'rate(request_duration_seconds_count{name="front-end", route="/", service="front-end", status_code="200"}[18s])'
APP_URL: "http://localhost:5000/"
UPDATE_DATA_ENDPOINT: "update_data"
PLOT_RESULTS_ENDPOINT: "plot_results"
UPDATE_INTERVAL_SEC: 10

#DUMMY
#START_TIME: datetime.datetime.strptime("2014-04-01 14:00:00", "%Y-%m-%d %H:%M:%S")
#END_TIME: datetime.datetime.strptime("2014-04-09 14:00:00", "%Y-%m-%d %H:%M:%S")
#METRIC_NAME: "value"
#APP_URL: "http://localhost:5000/"
#UPDATE_DATA_ENDPOINT: "update_data"
#PLOT_RESULTS_ENDPOINT: "plot_results"
#UPDATE_INTERVAL_SEC: 10
