---
apiVersion: v1
kind: Namespace
metadata:
  name: kad
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kad-config-file
  namespace: kad
data:
  config.yaml: |
    PROMETHEUS_URL: "http://prometheus.monitoring.svc.cluster.local:9090"
    START_TIME: "2021-10-14 18:18:00"
    END_TIME: "2021-10-14 18:30:00"
    METRIC_NAME: 'rate(request_duration_seconds_count{job="kubernetes-service-endpoints", kubernetes_name="front-end", kubernetes_namespace="sock-shop", method="get", name="front-end", route="/", service="front-end", status_code="200"}[1m])'
    APP_URL: "http://localhost:5000/"
    UPDATE_DATA_ENDPOINT: "update_data"
    GET_RESULTS_ENDPOINT: "get_results"
    PLOT_RESULTS_ENDPOINT: "plot_results"
    UPDATE_CONFIG_ENDPOINT: "update_config"
    UPDATE_INTERVAL_SEC: 5
    MODEL_NAME: "SarimaModel"
