---
apiVersion: v1
kind: Namespace
metadata:
  name: kad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
  labels:
    name: kad
  namespace: kad
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kad
  template:
    metadata:
      labels:
        name: kad
    spec:
      containers:
      - name: kad
        image: kad
        imagePullPolicy: Never
        command: ["python3", "kad/main.py"]
#        args: ["-c", "while true; do locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100 --no-web; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux
