---
apiVersion: v1
kind: Service
metadata:
  name: kad
  labels:
    name: kad
  namespace: kad
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31111
  selector:
    name: kad
